/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const MediaType = IDL.Variant({
  'movie' : IDL.Null,
  'videoGame' : IDL.Null,
  'tvShow' : IDL.Null,
});
export const Image = IDL.Variant({
  'embedded' : IDL.Vec(IDL.Nat8),
  'external' : ExternalBlob,
});
export const Time = IDL.Int;
export const MediaEntry = IDL.Record({
  'id' : IDL.Nat64,
  'review' : IDL.Opt(IDL.Text),
  'title' : IDL.Text,
  'owner' : IDL.Principal,
  'mediaType' : MediaType,
  'rating' : IDL.Opt(IDL.Nat),
  'image' : IDL.Opt(Image),
  'dateAdded' : Time,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const EmojiReaction = IDL.Record({
  'count' : IDL.Nat,
  'emoji' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addImageToMediaEntry' : IDL.Func(
      [IDL.Text, IDL.Nat64, ExternalBlob],
      [],
      [],
    ),
  'addReaction' : IDL.Func([IDL.Nat64, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createMediaEntry' : IDL.Func(
      [IDL.Text, MediaType, IDL.Opt(IDL.Nat), IDL.Opt(IDL.Text)],
      [IDL.Nat64],
      [],
    ),
  'getAllOfficialRecommendations' : IDL.Func(
      [],
      [IDL.Vec(MediaEntry)],
      ['query'],
    ),
  'getAllReviews' : IDL.Func([], [IDL.Vec(MediaEntry)], ['query']),
  'getBannerPhoto' : IDL.Func([], [IDL.Opt(ExternalBlob)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMediaEntriesByShareLink' : IDL.Func(
      [IDL.Nat64],
      [IDL.Vec(MediaEntry)],
      ['query'],
    ),
  'getMediaEntriesByUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(MediaEntry)],
      ['query'],
    ),
  'getReactionCounts' : IDL.Func(
      [IDL.Nat64],
      [IDL.Vec(EmojiReaction)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeReaction' : IDL.Func([IDL.Nat64, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setBannerPhoto' : IDL.Func([ExternalBlob], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const MediaType = IDL.Variant({
    'movie' : IDL.Null,
    'videoGame' : IDL.Null,
    'tvShow' : IDL.Null,
  });
  const Image = IDL.Variant({
    'embedded' : IDL.Vec(IDL.Nat8),
    'external' : ExternalBlob,
  });
  const Time = IDL.Int;
  const MediaEntry = IDL.Record({
    'id' : IDL.Nat64,
    'review' : IDL.Opt(IDL.Text),
    'title' : IDL.Text,
    'owner' : IDL.Principal,
    'mediaType' : MediaType,
    'rating' : IDL.Opt(IDL.Nat),
    'image' : IDL.Opt(Image),
    'dateAdded' : Time,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const EmojiReaction = IDL.Record({ 'count' : IDL.Nat, 'emoji' : IDL.Text });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addImageToMediaEntry' : IDL.Func(
        [IDL.Text, IDL.Nat64, ExternalBlob],
        [],
        [],
      ),
    'addReaction' : IDL.Func([IDL.Nat64, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createMediaEntry' : IDL.Func(
        [IDL.Text, MediaType, IDL.Opt(IDL.Nat), IDL.Opt(IDL.Text)],
        [IDL.Nat64],
        [],
      ),
    'getAllOfficialRecommendations' : IDL.Func(
        [],
        [IDL.Vec(MediaEntry)],
        ['query'],
      ),
    'getAllReviews' : IDL.Func([], [IDL.Vec(MediaEntry)], ['query']),
    'getBannerPhoto' : IDL.Func([], [IDL.Opt(ExternalBlob)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMediaEntriesByShareLink' : IDL.Func(
        [IDL.Nat64],
        [IDL.Vec(MediaEntry)],
        ['query'],
      ),
    'getMediaEntriesByUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(MediaEntry)],
        ['query'],
      ),
    'getReactionCounts' : IDL.Func(
        [IDL.Nat64],
        [IDL.Vec(EmojiReaction)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeReaction' : IDL.Func([IDL.Nat64, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setBannerPhoto' : IDL.Func([ExternalBlob], [], []),
  });
};

export const init = ({ IDL }) => { return []; };