/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const MediaType = IDL.Variant({
  'movie' : IDL.Null,
  'videoGame' : IDL.Null,
  'tvShow' : IDL.Null,
});
export const Time = IDL.Int;
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const MediaEntry = IDL.Record({
  'id' : IDL.Nat64,
  'review' : IDL.Opt(IDL.Text),
  'title' : IDL.Text,
  'owner' : IDL.Principal,
  'mediaType' : MediaType,
  'rating' : IDL.Opt(IDL.Nat),
  'dateAdded' : Time,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createMediaEntry' : IDL.Func(
      [IDL.Text, MediaType, IDL.Opt(IDL.Nat), IDL.Opt(IDL.Text)],
      [IDL.Nat64],
      [],
    ),
  'deleteMediaEntry' : IDL.Func([IDL.Nat64], [], []),
  'generateShareLink' : IDL.Func([IDL.Opt(Time)], [IDL.Nat64], []),
  'getAllProjectFilesZipBlob' : IDL.Func([], [IDL.Vec(IDL.Nat8)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMediaEntriesByShareLink' : IDL.Func(
      [IDL.Nat64],
      [IDL.Vec(MediaEntry)],
      ['query'],
    ),
  'getMediaEntriesByUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(MediaEntry)],
      ['query'],
    ),
  'getMyMediaEntries' : IDL.Func([], [IDL.Vec(MediaEntry)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'grantAccessToUser' : IDL.Func([IDL.Principal], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'revokeAccessFromUser' : IDL.Func([IDL.Principal], [], []),
  'revokeShareLink' : IDL.Func([IDL.Nat64], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateMediaEntry' : IDL.Func(
      [IDL.Nat64, IDL.Text, MediaType, IDL.Opt(IDL.Nat), IDL.Opt(IDL.Text)],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const MediaType = IDL.Variant({
    'movie' : IDL.Null,
    'videoGame' : IDL.Null,
    'tvShow' : IDL.Null,
  });
  const Time = IDL.Int;
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const MediaEntry = IDL.Record({
    'id' : IDL.Nat64,
    'review' : IDL.Opt(IDL.Text),
    'title' : IDL.Text,
    'owner' : IDL.Principal,
    'mediaType' : MediaType,
    'rating' : IDL.Opt(IDL.Nat),
    'dateAdded' : Time,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createMediaEntry' : IDL.Func(
        [IDL.Text, MediaType, IDL.Opt(IDL.Nat), IDL.Opt(IDL.Text)],
        [IDL.Nat64],
        [],
      ),
    'deleteMediaEntry' : IDL.Func([IDL.Nat64], [], []),
    'generateShareLink' : IDL.Func([IDL.Opt(Time)], [IDL.Nat64], []),
    'getAllProjectFilesZipBlob' : IDL.Func([], [IDL.Vec(IDL.Nat8)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMediaEntriesByShareLink' : IDL.Func(
        [IDL.Nat64],
        [IDL.Vec(MediaEntry)],
        ['query'],
      ),
    'getMediaEntriesByUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(MediaEntry)],
        ['query'],
      ),
    'getMyMediaEntries' : IDL.Func([], [IDL.Vec(MediaEntry)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'grantAccessToUser' : IDL.Func([IDL.Principal], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'revokeAccessFromUser' : IDL.Func([IDL.Principal], [], []),
    'revokeShareLink' : IDL.Func([IDL.Nat64], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateMediaEntry' : IDL.Func(
        [IDL.Nat64, IDL.Text, MediaType, IDL.Opt(IDL.Nat), IDL.Opt(IDL.Text)],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };