/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface MediaEntry {
  'id' : bigint,
  'review' : [] | [string],
  'title' : string,
  'owner' : Principal,
  'mediaType' : MediaType,
  'rating' : [] | [bigint],
  'dateAdded' : Time,
}
export type MediaType = { 'movie' : null } |
  { 'videoGame' : null } |
  { 'tvShow' : null };
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createMediaEntry' : ActorMethod<
    [string, MediaType, [] | [bigint], [] | [string]],
    bigint
  >,
  'deleteMediaEntry' : ActorMethod<[bigint], undefined>,
  'generateShareLink' : ActorMethod<[[] | [Time]], bigint>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMediaEntriesByShareLink' : ActorMethod<[bigint], Array<MediaEntry>>,
  'getMediaEntriesByUser' : ActorMethod<[Principal], Array<MediaEntry>>,
  'getMyMediaEntries' : ActorMethod<[], Array<MediaEntry>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'grantAccessToUser' : ActorMethod<[Principal], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'revokeAccessFromUser' : ActorMethod<[Principal], undefined>,
  'revokeShareLink' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateMediaEntry' : ActorMethod<
    [bigint, string, MediaType, [] | [bigint], [] | [string]],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];