/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface EmojiReaction { 'count' : bigint, 'emoji' : string }
export type ExternalBlob = Uint8Array;
export type Image = { 'embedded' : Uint8Array } |
  { 'external' : ExternalBlob };
export interface MediaEntry {
  'id' : bigint,
  'review' : [] | [string],
  'title' : string,
  'owner' : Principal,
  'mediaType' : MediaType,
  'rating' : [] | [bigint],
  'image' : [] | [Image],
  'dateAdded' : Time,
}
export type MediaType = { 'movie' : null } |
  { 'videoGame' : null } |
  { 'tvShow' : null };
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addImageToMediaEntry' : ActorMethod<
    [string, bigint, ExternalBlob],
    undefined
  >,
  'addReaction' : ActorMethod<[bigint, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createMediaEntry' : ActorMethod<
    [string, MediaType, [] | [bigint], [] | [string]],
    bigint
  >,
  'getAllOfficialRecommendations' : ActorMethod<[], Array<MediaEntry>>,
  'getAllReviews' : ActorMethod<[], Array<MediaEntry>>,
  'getBannerPhoto' : ActorMethod<[], [] | [ExternalBlob]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMediaEntriesByShareLink' : ActorMethod<[bigint], Array<MediaEntry>>,
  'getMediaEntriesByUser' : ActorMethod<[Principal], Array<MediaEntry>>,
  'getReactionCounts' : ActorMethod<[bigint], Array<EmojiReaction>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removeReaction' : ActorMethod<[bigint, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setBannerPhoto' : ActorMethod<[ExternalBlob], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];